"""Builds data/history.json from GVR monthly Stats Package PDFs.
Usage: python3 scripts/history-from-gvr.py <pdf> [<pdf> ...]
Reads the MLS® HPI tables (benchmark price + 1/3/6-month and 1-year changes) and the
Listing & Sales Activity Summary. Months not uploaded are filled from the changes reported
in neighbouring months (e.g. June = July price / (1 + July's 1-month change))."""
import json, re, subprocess, sys
MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December']
TYPE = {'Residential / Composite': 'composite', 'Single Family Detached': 'detached', 'Townhouse': 'townhome', 'Apartment': 'condo'}
ROW = re.compile(r'^\s*(?:(Residential / Composite|Single Family Detached|Townhouse|Apartment)\s+)?([A-Z][A-Za-z .]+?)\s+\$([\d,]+)\s+([\d.]+)\s+(-?[\d.]+)%\s+(-?[\d.]+)%\s+(-?[\d.]+)%\s+(-?[\d.]+)%')
def key_add(k, n): y, m = map(int, k.split('-')); m += n; y += (m - 1) // 12; m = (m - 1) % 12 + 1; return f'{y}-{m:02d}'
price, given, sales, listings = {}, {}, {}, {}
for pdf in sys.argv[1:]:
    txt = subprocess.run(['pdftotext', '-layout', pdf, '-'], capture_output=True, text=True).stdout
    m = re.search(r'(' + '|'.join(MONTHS) + r') (\d{4})', txt[txt.find('Benchmark') - 400: txt.find('Benchmark')] or txt)
    mon, yr = m.group(1), int(m.group(2)); k = f'{yr}-{MONTHS.index(mon) + 1:02d}'
    typ = None
    for line in txt.splitlines():
        r = ROW.match(line)
        if not r: continue
        if r.group(1): typ = TYPE[r.group(1)]
        area = r.group(2).strip()
        if area == 'Lower Mainland' or not typ: continue
        p = int(r.group(3).replace(',', '')); ch = {1: float(r.group(5)), 3: float(r.group(6)), 6: float(r.group(7)), 12: float(r.group(8))}
        price.setdefault(typ, {}).setdefault(area, {})[k] = p; given.setdefault(typ, {}).setdefault(area, {})[k] = True
        for n, c in ch.items():  # back-fill earlier months from reported changes (never overwrite a real figure)
            kk = key_add(k, -n)
            if not given[typ][area].get(kk): price[typ][area].setdefault(kk, round(p / (1 + c / 100) / 100) * 100)
    # Listing & Sales Activity Summary: area group, then DETACHED/ATTACHED/APARTMENTS rows
    s = txt.find('Listing & Sales Activity Summary'); grp = None
    for line in txt[s:].splitlines():
        g = re.match(r'^([A-Z][A-Z .&/-]+?)\s*(?:%.*)?$', line.strip())
        if g and g.group(1) not in ('DETACHED', 'ATTACHED', 'APARTMENTS') and len(g.group(1)) > 3: grp = g.group(1).title(); continue
        r = re.match(r'^\s*(DETACHED|ATTACHED|APARTMENTS)\s+([\d,]+)\s+([\d,]+)\s+([\d,]+)\s+(-?[\d.]+)\s+([\d,]+)\s+([\d,]+)\s+([\d,]+)', line)
        if r and grp:
            t = {'DETACHED': 'detached', 'ATTACHED': 'townhome', 'APARTMENTS': 'condo'}[r.group(1)]; n = lambda i: int(r.group(i).replace(',', ''))
            for kk, li, sa in ((key_add(k, -12), n(2), n(6)), (key_add(k, -1), n(3), n(7)), (k, n(4), n(8))):
                listings.setdefault(t, {}).setdefault(grp, {})[kk] = li; sales.setdefault(t, {}).setdefault(grp, {})[kk] = sa
srt = lambda d: {t: {a: dict(sorted(v.items())) for a, v in sorted(x.items())} for t, x in d.items()}
out = {'note': 'Benchmark prices: MLS® HPI from GVR Stats Packages; some months derived from reported % changes. Sales/new listings: GVR Listing & Sales Activity Summary.',
       'price': srt(price), 'sales': srt(sales), 'listings': srt(listings)}
json.dump(out, open('data/history.json', 'w'), indent=0)
open('data/history.js', 'w').write('// Generated by scripts/history-from-gvr.py from GVR Stats Packages. Do not edit by hand.\nexport default ' + json.dumps(out, separators=(',', ':')) + ';\n')
gv = out['price']['detached']['Greater Vancouver']; print('Detached GV months:', len(gv)); print({k: gv[k] for k in list(gv)[-14:]})
print('sales groups:', list(out['sales'].get('detached', {}).keys())[:30])
